### ISSUE TITLE
%%namespace not parsing

### ISSUE THREAD

**Issue by AnswerIsCoffee** [mikeboers/PyHAML#24]
Hi

I'm upgrading from ver 1.0.1 to 1.1.0, and a file that previously parsed is now throwing up errors. The line in question is:

%%namespace(file="file.haml", **{'import': '*'})

From reading the Mako docs, it appears that line should compile into the following:

<%namespace file="/file.haml" import="*"/>

Instead, I'm getting the following error:

SyntaxException: (SyntaxError) invalid syntax (<unknown>, line 1) (u"namespace<% __M_writer(__HAML.attribute_str({'__ad") in file xxx

I'm not sure if this is an error in my code, or something the parser cannot deal with. Any assistance would be greatly appreciated!

**Comment by DavidLemayian** [comment]
I'm getting this same error. Would appreciate if anyone has figured out an answer?

**Comment by mikeboers** [comment]
Okay, so... [this is the change that "broke" this behaviour](https://github.com/mikeboers/PyHAML/commit/f399002d796a5551816a4191c7f7cd1d9e1d67f8).

Options are either:

1. Add a few more hardcoded keywords that you can add an underscore postfix that is stripped. e.g. `import_` here like `class_`.

2. Better parsing.

**Comment by mikeboers** [comment]
I implemented the better parsing. Tests pass. Considering implementing option 1 as well...

**Comment by mikeboers** [comment]
I'm going to leave it there. v1.2.1 is on PyPI.
